// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7SammzoenY1_Z-N16I23CSnQpjsXD2n8',
    appId: '1:727951335686:android:eba54756ef29cf012afe87',
    messagingSenderId: '727951335686',
    projectId: 'vivas-apratments',
    storageBucket: 'vivas-apratments.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHnJheShc5bnkDsdrNlLGmPY7gxqsaeDY',
    appId: '1:727951335686:ios:641fe4e7ff1308a32afe87',
    messagingSenderId: '727951335686',
    projectId: 'vivas-apratments',
    storageBucket: 'vivas-apratments.appspot.com',
    androidClientId:
        '727951335686-c9ag5s59rhn2cltrptcutb54ut1p4s27.apps.googleusercontent.com',
    iosClientId:
        '727951335686-l8m1onjv103g42oofoa0316dvkablo8r.apps.googleusercontent.com',
    iosBundleId: 'com.studiflats.app',
  );
}
