# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:android)

platform :android do


  # Internal Testing Deployment
  desc "Upload to Google Play Internal Testing"
  lane :internal_test do
    # Extract current version name and code from pubspec.yaml
     version_line = File.read("../pubspec.yaml").match(/version: (\d+\.\d+\.\d+)\+(\d+)/)
     current_version_name = version_line[1] # e.g., "1.1.5"
     current_version_code = version_line[2].to_i # e.g., "23"

    # Increase the version code
     new_version_code = current_version_code + 1

    # Update pubspec.yaml with the new version
     new_version_string = "version: #{current_version_name}+#{new_version_code}"
     sh "sed -i '' 's/version: #{current_version_name}+#{current_version_code}/#{new_version_string}/' ../pubspec.yaml"

     sh"cd .. && flutter build appbundle"
    upload_to_play_store(
      track: "internal",   # Internal testing track
      json_key: "./fastlane/deploy.json",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      release_status: "draft",  # ✅ Use `release_status` instead

    )
  end

  # Production Deployment
  desc "Upload to Google Play Production"
  lane :production do
      sh"cd .. && flutter build appbundle"
    upload_to_play_store(
      track: "production",  # Production release
      json_key: "fastlane/deploy.json",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end

# default_platform(:android)
#
# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end
#
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
