name: Flutter Build & Upload to Play Store

on:
  push:
    branches:
      - CI-CD  # Change to your release branch
  workflow_dispatch:  # Enables manual trigger

jobs:
  build:
    name: Build & Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24"  # Change this based on your Flutter version

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Temurin is a reliable OpenJDK distribution
          java-version: '8'  # Use '11' or '17' based on your project's requirements

      - name: Verify Java Version
        run: java -version

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle

      - name: Upload AAB to Google Play (Optional)
        run: |
          cd android
          bundle install
          bundle exec fastlane internal_test
